name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    container: epitechcontent/epitest-docker:devel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake with coverage infos
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_CODE_COVERAGE=ON

      - name: Build
        run: cmake --build ./build -j 10

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Collect coverage files
        run: |
          find build -iname "*.gcno" -exec cp {} . \;
          find build -iname "*.gcda" -exec cp {} . \;
          gcovr . --exclude-unreachable-branches --exclude-throw-branches --xml --output ./coverage.xml --exclude tests/

      - uses: codecov/codecov-action@v2
        with:
          path: coverage.xml